services:
  app:
    build: .
    image: find:latest
    environment:
      SEARCH_DB: '/opt/find/search.db'
      TZ: 'Europe/Rome'
      FLASK_DEBUG: false
      REINDEX_INTERVAL_HOURS: 8
    ports:
      - "49152:7001"
    # Ensure around 2 cpu - 10%
    cpus: 1.90
    volumes:
      - /opt/find:/opt/find
    # logging:
    #   driver: syslog
    #   options:
    #     tag: "find"
    #     syslog-facility: "16"      
